var coins = [
    {
        "name":"UDAO",
        "logo":"./images/coin/coin_0.png",
        "shortName":"UDAO",
    },
    {
        "name":"Bitcion",
        "logo":"./images/coin/coin_13.png",
        "shortName":"BTC",
    },
    {
        "name":"Bitcion Cash",
        "logo":"./images/coin/coin_13.png",
        "shortName":"BCH",
    },
    {
        "name":"TRON",
        "logo":"./images/coin/coin_9.png",
        "shortName":"TRX",
    },
    {
        "name":"Ethereum",
        "logo":"./images/coin/coin_4.png",
        "shortName":"ETH",
    },
    {
        "name":"Binance Coin",
        "logo":"./images/coin/coin_7.png",
        "shortName":"BNB",
    },
    {
        "name":"Dash",
        "logo":"./images/coin/coin_10.png",
        "shortName":"DASH",
    },
    {
        "name":"Ripple",
        "logo":"./images/coin/coin_5.png",
        "shortName":"XRP",
    },
    {
        "name":"Tether",
        "logo":"./images/coin/coin_1.png",
        "shortName":"USDT",
    },
    {
        "name":"Loopring",
        "logo":"./images/coin/coin_11.png",
        "shortName":"LRC",
    },
    {
        "name":"Litecoin",
        "logo":"./images/coin/coin_6.png",
        "shortName":"LTC",
    },
    {
        "name":"EOS",
        "logo":"./images/coin/coin_8.png",
        "shortName":"EOS",
    },
    {
        "name":"Qtum",
        "logo":"./images/coin/coin_12.png",
        "shortName":"QTUM",
    },
];