var coins = [
    {
        "name":"UDAO",
        "logo":"./images/coin/coin_0.png",
        "shortName":"UDAO",
    },
    {
        "name":"Ethereum",
        "logo":"./images/coin/coin_4.png",
        "shortName":"ETH",
    },
    {
        "name":"Dai",
        "logo":"./images/coin/dai.png",
        "shortName":"DAI",
    },
    {
        "name":"wBTC",
        "logo":"./images/coin/wbtc.png",
        "shortName":"WBTC",
    },
    {
        "name":"Basic Attention Token",
        "logo":"./images/coin/bat.png",
        "shortName":"BAT",
    },
    {
        "name":"Maker",
        "logo":"./images/coin/mkr.png",
        "shortName":"MKR",
    },
    {
        "name":"TokenCard",
        "logo":"./images/coin/tkn.png",
        "shortName":"TKN",
    },
    {
        "name":"TrueUSD",
        "logo":"./images/coin/tusd.png",
        "shortName":"TUSD",
    },
    {
        "name":"SpankChain",
        "logo":"./images/coin/spank.png",
        "shortName":"SPANK",
    },
    {
        "name":"USD Coin",
        "logo":"./images/coin/usdc.png",
        "shortName":"USDC",
    },
    {
        "name":"SNX",
        "logo":"./images/coin/snx.png",
        "shortName":"SNX",
    },
    {
        "name":"Augur",
        "logo":"./images/coin/rep.png",
        "shortName":"REP",
    },
    {
        "name":"Digix Gold Token",
        "logo":"./images/coin/dgx.png",
        "shortName":"DGX",
    },
    {
        "name":"Aragon",
        "logo":"./images/coin/ant.png",
        "shortName":"ANT",
    },
    {
        "name":"ChainLink",
        "logo":"./images/coin/link.png",
        "shortName":"LINK",
    },
    {
        "name":"Gnosis",
        "logo":"./images/coin/gno.png",
        "shortName":"GNO",
    },
    {
        "name":"Loopring",
        "logo":"./images/coin/lrc.png",
        "shortName":"LRC",
    },
    {
        "name":"0x",
        "logo":"./images/coin/0x.png",
        "shortName":"ZRX",
    },
    {
        "name":"FunFair",
        "logo":"./images/coin/fun.png",
        "shortName":"FUN",
    },
    {
        "name":"DAOstack",
        "logo":"./images/coin/gen.png",
        "shortName":"GEN",
    },
];